### ISSUE TITLE
スラッシュコマンドとプレフィックスコマンドで別々のキューになる問題

### ISSUE THREAD

**Issue by MotiCAT** [MotiCAT/TuneNekoSync#6]
どう要約すればいいか分からないが、こう↓
- 音楽のキュー自体は共有されている。
- ただ、それ以外が全く共有されていなく、例えば、プレフィックスコマンドで再生を始めた場合、スラッシュコマンドでキューに追加しても「キューに追加しました」ではなく「再生します」になる。
- その他、キューコマンドを実行しても共有されていなかったり、途中退出やstopしたりすると挙句の果てには再生すらできなくなる。

**Comment by MotiCAT** [comment]
別件ですがたまにqueueのレスポンスが遅れるのでdeferしときます。

**Comment by Nich87** [comment]
playerがそれぞれ独立しているが故に発生していると思われます。
改めて確認してPR投げます。
